import Link from 'next/link'

const topStyles = [
  {
    name: 'LinkedIn Professional profile headshot',
    image: '/pro-result.jpg',
    border: 'border-purple-500/30',
    glow: 'hover:border-purple-400',
  },
  {
    name: 'Goth alternative AI portrait',
    image: '/goth-result.jpg',
    border: 'border-pink-500/30',
    glow: 'hover:border-pink-400',
  },
  {
    name: 'Anime AI avatar',
    image: '/anime-result.jpg',
    border: 'border-green-500/30',
    glow: 'hover:border-green-400',
  },
]

const allStyles = [
  'LinkedIn Profile', 'Alt / Goth', 'Anime', 'Fairycore', 'Grunge', 'Indie Sleaze',
  'Cottagecore', 'Cyberpunk', 'Dark Academia', 'Maximalist', 'Minimalist', 'Vaporwave',
]

const badgeColors = [
  'from-purple-600 to-purple-400',
  'from-pink-600 to-pink-400',
  'from-green-600 to-green-400',
]

export default function Hero() {
  return (
    <section id="styles" className="relative pb-8 overflow-hidden scroll-mt-32">
      <div className="container mx-auto px-6 text-center">
        <div className="mb-6">
          <p className="text-xl md:text-2xl text-purple-300 mb-2 font-medium">
            LinkedIn, Goth, Anime, Cyberpunk, Vaporwave{' '}
            <span className="bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text text-transparent">
              &amp; 7 More AI Styles
            </span>
          </p>
          <p className="text-base text-gray-400">
            Upload a photo, pick your aesthetic, and generate a stunning AI profile picture in seconds. 100% free daily credit, face-preserving InstantID technology.
          </p>
        </div>

        <div className="max-w-6xl mx-auto text-center mb-12 py-8">
          <h1 className="text-3xl md:text-4xl font-bold text-white mb-2">
            Free AI Profile Picture Generator
          </h1>
          <h2 className="text-2xl md:text-3xl font-semibold text-transparent bg-clip-text bg-gradient-to-r from-purple-400 via-pink-400 to-cyan-400 mb-4">
            12 Stunning Styles — From LinkedIn to Vaporwave
          </h2>
          <p className="text-4xl md:text-6xl font-black text-white tracking-tight leading-none">
            All Generated in Seconds
          </p>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mt-12 max-w-5xl mx-auto">
            {topStyles.map((style, i) => (
              <div key={style.name} className="group relative">
                <span className={`bg-gradient-to-r ${badgeColors[i]} px-3 py-1 rounded-full text-xs font-bold shadow-lg absolute -top-3 -left-3 z-10`}>
                  0{i + 1}
                </span>
                <div className={`relative aspect-[4/5] rounded-2xl overflow-hidden border-4 ${style.border} ${style.glow} shadow-2xl transition-all duration-500 group-hover:shadow-3xl group-hover:-translate-y-2`}>
                  <img
                    src={style.image}
                    alt={`${style.name} generated by FreePFP.ai`}
                    className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-110"
                    loading="lazy"
                    width="400"
                    height="500"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/20 to-transparent"></div>
                  <div className="absolute bottom-0 left-0 right-0 p-6">
                    <p className="text-xl md:text-2xl font-bold text-white text-center drop-shadow-lg">
                      {style.name}
                    </p>
                  </div>
                </div>
              </div>
            ))}
          </div>

          <Link href="/transform">
            <button className="mt-16 px-10 py-5 bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700 text-white font-bold text-xl rounded-xl shadow-2xl hover:shadow-purple-500/50 transform hover:scale-110 transition-all duration-300">
              TRY IT NOW — 1 FREE PER DAY
            </button>
          </Link>
        </div>

        <div className="max-w-3xl mx-auto mt-8 text-left prose prose-invert">
          <h2 className="text-xl font-semibold text-white mb-3">How to Make AI Profile Pictures on FreePFP.ai</h2>
          <p className="text-gray-400 text-sm leading-relaxed">
            FreePFP.ai is a free{' '}
            <strong className="text-white">AI profile picture generator</strong> that uses{' '}
            <strong className="text-white">InstantID face-preserving technology</strong> to
            transform your photo into professional{' '}
            <span className="text-purple-300">LinkedIn headshots</span>, anime avatars, goth
            portraits, cyberpunk styles, vaporwave looks, and 7 more aesthetics. Upload any
            clear photo of yourself, choose a style, and get a high-resolution AI-generated
            profile picture in under 30 seconds. One free transformation every day — no credit
            card required.
          </p>
        </div>
      </div>
    </section>
  )
}
